### ISSUE TITLE
Issue with taskbar integratio (doesnt happen with the aur pkg)

### ISSUE THREAD

**Issue by Twig6943** [pkgforge-dev/Cromite-AppImage#1]
Nothing happens when I click on it

I can open it from the start menu tho

https://github.com/user-attachments/assets/75177f31-0ed6-4c94-aa17-b5f42579c261

**Comment by Samueru-sama** [comment]
did you install with am/appman? 

can you copy and paste the contents of `.desktop` file?

**Comment by Twig6943** [comment]
> did you install with am/appman?
> 
> can you copy and paste the contents of `.desktop` file?

1.Yes I did

2.
[Desktop Entry]
Version=1.0
Encoding=UTF-8
Name=Cromite
Exec=cromite %U
Terminal=false
Icon=/opt/cromite/icons/cromite
Type=Application
Categories=Application;Network;WebBrowser;
MimeType=text/html;text/xml;application/xhtml_xml;

**Comment by Samueru-sama** [comment]
> > did you install with am/appman?
> > can you copy and paste the contents of `.desktop` file?
> 
> 1.Yes I did
> 
> 
> [Desktop Entry] Version=1.0 Encoding=UTF-8 Name=Cromite Exec=cromite %U Terminal=false Icon=/opt/cromite/icons/cromite Type=Application Categories=Application;Network;WebBrowser; MimeType=text/html;text/xml;application/xhtml_xml;

Do the following, remove the appimage and install it again with am/appman. 

I think I fixed your [issue already before this was even opened](https://github.com/pkgforge-dev/Cromite-AppImage/issues/1) lol

**Comment by Twig6943** [comment]
@Samueru-sama yep reinstalling with AM got it fixed. Turns out I was using an old version

**Comment by Samueru-sama** [comment]
Just so you know, I pushed that fix because @contrarybaton60 had the same issue with the [Steam AppImage](https://github.com/ivan-hc/Steam-appimage/issues/47).

But it was too late anyway lol.
